name: Build ticker dredge_heds.json

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"  # run every 15 minutes

permissions:
  contents: write

concurrency:
  group: ticker-publish
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo tree (top-level and likely places)
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
          echo "---- newsriver/"
          ls -la newsriver || true
          echo "---- newsriver/scripts/"
          ls -la newsriver/scripts || true
          echo "---- locate fetch_tickerlines.py"
          find . -maxdepth 4 -type f -name "fetch_tickerlines.py" -print || true
          echo "---- locate headlines.json"
          find . -maxdepth 4 -type f -name "headlines.json" -print || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (ticker)
        run: |
          python -m pip install --upgrade pip
          if [[ -f newsriver/scripts/requirements-ticker.txt ]]; then
            pip install -r newsriver/scripts/requirements-ticker.txt
          elif [[ -f newsriver/scripts/requirements.txt ]]; then
            pip install -r newsriver/scripts/requirements.txt
          else
            pip install feedparser requests python-dateutil beautifulsoup4
          fi

      - name: Ensure output directory exists
        run: |
          mkdir -p newsriver/newsriver

      - name: Locate script and input; run build
        run: |
          set -e

          # 1) Locate the script (prefer the expected path)
          if [[ -f "newsriver/scripts/fetch_tickerlines.py" ]]; then
            SCRIPT_PATH="newsriver/scripts/fetch_tickerlines.py"
          else
            SCRIPT_PATH="$(find . -maxdepth 4 -type f -name 'fetch_tickerlines.py' | head -n1 || true)"
          fi
          if [[ -z "$SCRIPT_PATH" ]]; then
            echo "ERROR: fetch_tickerlines.py not found under repo root." >&2
            exit 2
          fi
          echo "Using script: $SCRIPT_PATH"

          # 2) Locate input headlines.json (script default expects ./newsriver/headlines.json)
          DEFAULT_IN="./newsriver/headlines.json"
          if [[ -f "$DEFAULT_IN" ]]; then
            INPATH="$DEFAULT_IN"
          else
            INPATH="$(find . -maxdepth 4 -type f -name 'headlines.json' | head -n1 || true)"
          fi
          if [[ -z "$INPATH" ]]; then
            echo "ERROR: headlines.json not found (expected at $DEFAULT_IN)." >&2
            exit 3
          fi
          echo "Using input: $INPATH"

          # 3) Canonical output used by frontend/validator
          OUTPATH="./newsriver/newsriver/dredge_heds.json"

          python "$SCRIPT_PATH" --in "$INPATH" --out "$OUTPATH"

      - name: Validate dredge_heds.json
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs'); // 'core' is provided by github-script v7

            const p = 'newsriver/newsriver/dredge_heds.json';
            if (!fs.existsSync(p)) {
              core.setFailed(`ERROR: ${p} not found`);
              return;
            }

            let data;
            try {
              data = JSON.parse(fs.readFileSync(p, 'utf8'));
            } catch (e) {
              core.setFailed(`ERROR: cannot parse ${p}: ${e.message}`);
              return;
            }

            const items = (data && Array.isArray(data.items)) ? data.items : [];
            if (!Array.isArray(items)) {
              core.setFailed('ERROR: items is not a list');
              return;
            }
            if (items.length < 3) {
              core.setFailed(`ERROR: items has length ${items.length} (<3). Abort publish.`);
              return;
            }
            for (let i = 0; i < items.length; i++) {
              const it = items[i] || {};
              const url = typeof it.url === 'string' ? it.url.trim() : '';
              const title = (it.display || it.text || it.hyped || it.title || '').trim();
              if (!url) {
                core.setFailed(`ERROR: item ${i} missing valid url`);
                return;
              }
              if (!title) {
                core.setFailed(`ERROR: item ${i} missing display/text/title`);
                return;
              }
            }
            core.info('Validation OK: dredge_heds.json');

      - name: Commit and push if changed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add newsriver/newsriver/dredge_heds.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ticker: update dredge_heds.json [ci skip]"
            git push
          fi
