name: Build NBA JSON

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Fetch NBA
        run: python scripts/fetch_nba.py

      - name: Copy to repo root for Pages
        run: cp newsriver/nba.json nba.json

      - name: Commit & push if changed (with rebase)
        run: |
          set -e
          if [ -n "$(git status --porcelain -- newsriver/nba.json nba.json)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add newsriver/nba.json nba.json
            git commit -m "chore: refresh NBA json"

            for attempt in 1 2 3; do
              git pull --rebase --autostash origin main && \
              git push origin HEAD:main && exit 0
              echo "Push race, retrying ($attempt)…"; sleep 2
            done
            git pull --rebase --autostash origin main
            git push origin HEAD:main
          else
            echo "No NBA changes."
          fi
