name: Enrich headlines.json

on:
  push:
    branches: [ main ]
    paths:
      - 'headlines.json'
      - 'scripts/**'
      - '.github/workflows/enrich.yml'
  workflow_dispatch: {}  # allow manual runs from the Actions tab

jobs:
  enrich:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow the workflow to commit back to the repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Enrich headlines.json
        run: |
          python scripts/enrich_headlines.py headlines.json --inplace

      - name: Commit enriched JSON (if changed)
        run: |
          if ! git diff --quiet -- headlines.json; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add headlines.json
            git commit -m "CI: enrich headlines.json (canonical_url/cluster_id/paywall/opinion)"
            git push
          else
            echo "No enrichment changes."
          fi
