name: NewsRiver: build headlines.json

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes

permissions:
  contents: write

# Prevent two runs from editing headlines.json at the same time
concurrency:
  group: newsriver-headlines
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # Start from the latest remote to avoid rebase/merge conflicts
      - name: Sync to remote main
        run: |
          git fetch origin
          git checkout main || git checkout -b main
          git reset --hard origin/main
          git status -sb

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -V
          python -m pip install --upgrade pip wheel setuptools
          pip install feedparser

      - name: Build headlines.json
        env:
          # Leave empty for normal mode. To test fast, set SMOKE to "1".
          SMOKE: ""
        run: python build_headlines.py

      - name: Commit & push (no rebase)
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "ci: refresh headlines.json"
            git push origin HEAD:main
          fi
