name: Build headlines.json

on:
  workflow_dispatch:
    inputs:
      smoke:
        description: 'Use SMOKE mode (fast test)'
        type: boolean
        default: true
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -V
          python -m pip install --upgrade pip wheel setuptools
          pip install feedparser pyyaml

      # Set SMOKE=1 only when the run was manually dispatched AND the checkbox is true.
      # Scheduled runs will use SMOKE=0 (full run).
      - name: Configure SMOKE env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.smoke }}" == "true" ]]; then
            echo "SMOKE=1" >> "$GITHUB_ENV"
            echo "Running in SMOKE mode"
          else
            echo "SMOKE=0" >> "$GITHUB_ENV"
            echo "Running in FULL mode"
          fi

      - name: Build headlines.json
        run: python build_headlines.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "ci: refresh headlines.json"
            git pull --rebase --autostash || true
            git push
          else
            echo "No changes to commit."
          fi
