name: Build tour.json

on:
  schedule:
    - cron: "15 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run fetch:60d

      - name: Commit tour.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(tour): refresh events"
          file_pattern: tour.json
